# 配置文件
print=true
debug=true

[logger]
tty=true
# file=true
# text, json, line
# type="line"
# syslog, file, stdout(默认)
kind="file"
# file 输出日志文件路径，默认为 ./logs
folder="./dist/logs"
# syslog="udp://klog.default.svc:5141"

[server]
local = true
port = 81
# addr = "0.0.0.0"
# engine=rdx
xrt="2"
# api="api/v1"

[sqlx]
# ksqldebug="true"
showsql="true"
