name: build-all

on:
  push:
    # branches: [ main ]? | tags: [ "*-*" ]?
    tags: [ "v*" ]

env:
  GITHUB_REGISTRY: ghcr.io
  # IMAGE_NAME: suisrc/k8skit
  # DOCKER_REGISTRY: docker.io

permissions:
  packages: write # GHCR 镜像包写入权限（推送镜像核心）

jobs:
  zoant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use build
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # docker_user: ${{ secrets.DOCKER_USER }}
          # docker_token: ${{ secrets.DOCKER_TOKEN }}
